title: Joni Halabi
email: joni@jhalabi.com
description: >- # this means to ignore newlines
  Personal site that includes my resume, work as a web developer, and
  blog articles about tech and life.
production_url: https://jhalabi.com

twitter_username: jonihalabi
github_username:  thatdevgirl
timezone: America/New_York

icons: '/assets/icons'
images: '/assets/images'

permalink: /blog/:title
paginate: 20
paginate_path: "/blog/page:num/"

highlighter: rouge

sass:
  sass_dir: '/assets/_sass'
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate
