title: Joni Halabi
email: joni@jhalabi.com
description: >- # this means to ignore newlines
  Personal site that includes my resume, work as a web developer, and
  blog articles about tech and life.
production_url: https://jonihalabi.com

twitter_username: jonihalabi
github_username:  thatdevgirl

icons: '/assets/icons'
images: '/assets/images'

permalink: /writing/:title

sass:
  sass_dir: '/assets/_sass'
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 20
paginate_path: "/writing/page:num/"
