title: Joni Halabi
email: joni@jhalabi.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal site that includes my resume, work as a web developer, and
  blog articles about tech and life.
production_url: https://jonihalabi.com

twitter_username: jonihalabi
github_username:  thatdevgirl

icons: '/assets/icons'
images: '/assets/images'

sass:
  sass_dir: '/assets/_sass'
  style: compressed

plugins:
  - jekyll-feed
